### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by vallettea** [PredictionIO/template-scala-parallel-classification#2]
Hello,

when I run 

```
python data/import_eventserver.py --access_key ...
```

I get a `IOError: [Errno 2] No such file or directory: './data/data.txt'` 

Where should i download the data from ?

**Comment by k4hoo** [comment]
Hi @vallettea ,
sorry about the missing sample data.txt. we just updated new release with data.
you could also find the sample data here
https://github.com/PredictionIO/template-scala-parallel-classification/blob/v0.1.3/data/data.txt

**Comment by vallettea** [comment]
No pb, thx for the reply.
